version: "3"
services:
  mqtt:
    image: arm32v6/eclipse-mosquitto
    restart: unless-stopped
    container_name: "MQTT"
    ports:
      - 1883:1883
      - 9001:9001
    expose:
      - 1883
  
  ui:
    build:
      context: ./web   
    ports:
      - 5050:5050
    volumes:
      - ./web/sources:/app
    container_name: web_server