version: "3"
services:
  mqtt:
    image: arm32v6/eclipse-mosquitto
    restart: unless-stopped
    container_name: "MQTT"
    ports:
      - 1883:1883
      - 9001:9001
    expose:
      - 1883
  
  ui:
    build:
      context: ./ui_server   
    ports:
      - 5001:5001
    volumes:
      - ./ui_server/sources:/app
    container_name: basic_ui